objects/Feature__c.object
<CustomObject>
    <description>A movie being shown</description>
    <fields>
        <fullName>Genre__c</fullName>
        <label>Genre</label>
        <picklist>
            <picklistValues>
                <fullName>Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adventure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comedy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Musical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science Fiction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>War</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Showing__c.object
<CustomObject>
    <description>The playing of a Feature in a Theatre</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feature</label>
        <referenceTo>Feature__c</referenceTo>
        <relationshipLabel>Showings</relationshipLabel>
        <relationshipName>Showings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Screen_Number__c</fullName>
        <label>Screen Number</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <picklist>
            <picklistValues>
                <fullName>4:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30 PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tickets_Sold__c</fullName>
        <label>Tickets Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Showing</label>
    <nameField>
        <label>Showing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestShowingWizardController.cls
@isTest public class TestShowingWizardController { 
	static testmethod void TestController(){
		List<Feature__c> features = new List<Feature__c>();
		for(integer i = 0; i < 10; i++){
			features.add(TestDataGenerator.CreateFeature('test ' + i, 'Action', date.today().addDays(-i)));
			features.add(TestDataGenerator.CreateFeature('test ' + i, 'Comedy', date.today().addDays(-i)));
			features.add(TestDataGenerator.CreateFeature('test ' + i, 'Drama',  date.today().addDays(-i)));
		}
		insert features;

		PageReference pageRef = Page.ShowingWizard;
		Test.setCurrentPage(pageRef);
		Showing__c showing = new Showing__c();
		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(showing);
		ShowingWizardController ctrl = new ShowingWizardController(stdCtrl);
		ctrl.FilterFeatures();
		system.assertEquals(6, ctrl.totalPages);

		ctrl.ShowNext();
		system.assertEquals(2, ctrl.currentPage);
		ctrl.ShowPrevious();
		ctrl.ShowLast();
		system.assert(ctrl.lastRendered);
		ctrl.ShowFirst();
		system.assert(ctrl.firstRendered);

		system.assert(ctrl.getGenres().size() > 0);

		system.assertEquals(false, ctrl.isAtLeastOneFeatureSelected);
		ctrl.featureId2Selected.put(features[5].Id, true);
		system.assertEquals(true, ctrl.isAtLeastOneFeatureSelected);

		List<ShowingWizardController.GenreWedgeData> genreData = ctrl.GetPieData();
		system.assertEquals(1, genreData.size());
		system.assertEquals(features[5].genre__c, genreData[0].genre);
		system.assertEquals(1, genreData[0].cnt);

		ctrl.selectedGenre = 'Action';
		ctrl.FilterFeatures();
		system.assertEquals(2, ctrl.totalPages);
		system.assertEquals(10, ctrl.setCon.getResultSize());

		showing.Start_Time__c = '4:30 PM';
		showing.Feature__c = features[4].Id;
		showing.Screen_Number__c = '5';
		showing.Tickets_Sold__c = 100;
		showing.Date__c = Date.today().addDays(-50);
		ctrl.Save();//negative use case, should not save successfuly 
		System.assertEquals(0, [select Date__c, start_time__c, feature__c, screen_number__c, tickets_sold__c from Showing__c where id =: showing.id].size());
		showing.Date__c = Date.today();
		ctrl.Save();//Positive use case, save should succeed

		Showing__c savedShowing = [select Date__c, start_time__c, feature__c, screen_number__c, tickets_sold__c from Showing__c where id =: showing.id];
		system.assertEquals(showing.Start_Time__c, savedShowing.Start_Time__c);
		system.assertEquals(showing.Feature__c, savedShowing.Feature__c);
		system.assertEquals(showing.Screen_Number__c, savedShowing.Screen_Number__c);
		system.assertEquals(showing.Tickets_Sold__c, savedShowing.Tickets_Sold__c);

		stdCtrl = new ApexPages.StandardController(savedShowing);
		ctrl = new ShowingWizardController(stdCtrl);
		integer cntSelectedFeatures = 0;
		for(Id featureId : ctrl.featureId2Selected.keySet()){
			if(ctrl.featureId2Selected.get(featureId)){
				cntSelectedFeatures++;
			}
		}
		system.assertEquals(1, cntSelectedFeatures);

		ctrl.selectedGenre = 'Action';
		ctrl.FilterFeatures();
		system.assertEquals(1, ctrl.totalPages);
		system.assertEquals(1, ctrl.setCon.getResultSize());
	}
}