objects/Feature__c.object
<CustomObject>
    <description>A movie being shown</description>
    <fields>
        <fullName>Genre__c</fullName>
        <label>Genre</label>
        <picklist>
            <picklistValues>
                <fullName>Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adventure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comedy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Musical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science Fiction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>War</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Showing__c.object
<CustomObject>
    <description>The playing of a Feature in a Theatre</description>
    <fields>
        <fullName>Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feature</label>
        <referenceTo>Feature__c</referenceTo>
        <relationshipLabel>Showings</relationshipLabel>
        <relationshipName>Showings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Genre__c</fullName>
        <label>Primary Genre</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Showing</label>
    <nameField>
        <label>Showing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Trailer__c.object
<CustomObject>
    <description>A one-minute preview of a to-be-released Feature that is shown prior to the primary Feature of a Showing.</description>
    <fields>
        <fullName>Feature__c</fullName>
        <label>Feature</label>
        <referenceTo>Feature__c</referenceTo>
        <relationshipLabel>Trailers</relationshipLabel>
        <relationshipName>Trailers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Showing__c</fullName>
        <label>Showing</label>
        <referenceTo>Showing__c</referenceTo>
        <relationshipLabel>Trailers</relationshipLabel>
        <relationshipName>Trailers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Trailer</label>
    <nameField>
        <label>Trailer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TrailerHandler.cls
public class TrailerHandler extends BaseTriggerHandler { 
	
	protected override void AfterInsert(){
		SetPrimaryGenre(null);
	}

	protected override void AfterUpdate(){
		SetPrimaryGenre(null);
	}

	protected override void AfterDelete(){
		Set<Id> showingIds = new Set<Id>();
		for(SObject s : trigger.old){
			showingIds.add(((Trailer__c)s).showing__c);
		}
		SetPrimaryGenre(showingIds);
	}

	protected override void AfterUndelete(){
		SetPrimaryGenre(null);
	}
	
	private void SetPrimaryGenre(Set<Id> showingIds ){
		if(showingIds == null){
			showingIds = new Set<Id>();
			for(Sobject s : trigger.new){
				showingIds.add(((Trailer__c)s).showing__c);
			}
		}
		
		List<AggregateResult> aggs = [select showing__c, count(showing__r.name) cnt, feature__r.genre__c primaryGenre 
									from trailer__c 
									where showing__c in: showingIds 
									group by rollup(showing__c, feature__r.genre__c) 
									order by showing__c, count(showing__r.name) desc, feature__r.genre__c asc];

		Map<Id, string> showingId2PrimaryGenre = new Map<Id, string>();
		for(AggregateResult agg : aggs){
			if(agg.get('showing__c') != null && agg.get('primaryGenre') != null && !showingId2PrimaryGenre.containsKey((Id)agg.get('showing__c'))){
				showingId2PrimaryGenre.put((Id)agg.get('showing__c'), String.valueOf(agg.get('primaryGenre')));
			}
		}

		List<Showing__c> showings2Update = new List<Showing__c>();
		for(Id showingId : showingIds){
			if(showingId2PrimaryGenre.containsKey(showingId)){
				showings2Update.add(new Showing__c(Id = showingId, primary_genre__c = showingId2PrimaryGenre.get(showingId)));
			}else{
				showings2Update.add(new Showing__c(Id = showingId, primary_genre__c = ''));//here empty string because of requirement but it will be saved as NULL!
			}
		}
		update showings2Update;
	}
}