objects/Feature__c.object
<CustomObject>
    <description>A movie being shown</description>
    <fields>
        <fullName>Genre__c</fullName>
        <label>Genre</label>
        <picklist>
            <picklistValues>
                <fullName>Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adventure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comedy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Musical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science Fiction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>War</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Showing__c.object
<CustomObject>
    <description>The playing of a Feature in a Theatre</description>
    <fields>
        <fullName>Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feature</label>
        <referenceTo>Feature__c</referenceTo>
        <relationshipLabel>Showings</relationshipLabel>
        <relationshipName>Showings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Genre__c</fullName>
        <label>Primary Genre</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Showing</label>
    <nameField>
        <label>Showing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Trailer__c.object
<CustomObject>
    <description>A one-minute preview of a to-be-released Feature that is shown prior to the primary Feature of a Showing.</description>
    <fields>
        <fullName>Feature__c</fullName>
        <label>Feature</label>
        <referenceTo>Feature__c</referenceTo>
        <relationshipLabel>Trailers</relationshipLabel>
        <relationshipName>Trailers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Showing__c</fullName>
        <label>Showing</label>
        <referenceTo>Showing__c</referenceTo>
        <relationshipLabel>Trailers</relationshipLabel>
        <relationshipName>Trailers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Trailer</label>
    <nameField>
        <label>Trailer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestTrailerTrigger.cls
@isTest public class TestTrailerTrigger { 
	static testmethod void TestShowingGenre(){

		List<Feature__c> features = TestDataGenerator.CreateFeaturs(4);
		features[0].Genre__c = 'Action';
		features[1].Genre__c = 'Comedy';
		features[2].Genre__c = 'Drama';
		features[3].Genre__c = 'Drama';
		insert features;

		Showing__c showing = TestDataGenerator.CreateShowings(features[3].Id, 1)[0];
		insert showing;

		List<Trailer__c> trailers = new List<Trailer__c>();
		trailers.add(TestDataGenerator.CreateTrailer(features[0].Id, showing.Id));
		trailers.add(TestDataGenerator.CreateTrailer(features[0].Id, showing.Id));
		trailers.add(TestDataGenerator.CreateTrailer(features[1].Id, showing.Id));
		trailers.add(TestDataGenerator.CreateTrailer(features[2].Id, showing.Id));
		insert trailers;

		showing = [select primary_genre__c from Showing__c where id =: showing.Id];
		System.assertEquals('Action', showing.Primary_Genre__c);

		delete trailers;
		showing = [select primary_genre__c from Showing__c where id =: showing.Id];
		System.assertEquals(null, showing.Primary_Genre__c);// per requirement should be empty string but it is always saves as NULL in DB
		
		//Requirement to support undelete of Trailers. Afer undeleting trailers primary genre has to be same as before deleting
		undelete trailers;
		System.assertEquals(4, [select id from Trailer__c].size());

		showing = [select primary_genre__c from Showing__c where id =: showing.Id];
		System.assertEquals('Action', showing.Primary_Genre__c);
	}
}