objects/Feature__c.object
<CustomObject>
    <description>A movie being shown</description>
    <fields>
        <fullName>Trailer_Impressions__c</fullName>
        <label>Trailer Impressions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Showing__c.object
<CustomObject>
    <description>The playing of a Feature in a Theatre</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feature</label>
        <referenceTo>Feature__c</referenceTo>
        <relationshipLabel>Showings</relationshipLabel>
        <relationshipName>Showings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <picklist>
            <picklistValues>
                <fullName>4:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30 PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tickets_Sold__c</fullName>
        <label>Tickets Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Showing</label>
    <nameField>
        <label>Showing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Trailer__c.object
<CustomObject>
    <description>A one-minute preview of a to-be-released Feature that is shown prior to the primary Feature of a Showing.</description>
    <fields>
        <fullName>Feature__c</fullName>
        <label>Feature</label>
        <referenceTo>Feature__c</referenceTo>
        <relationshipLabel>Trailers</relationshipLabel>
        <relationshipName>Trailers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Showing__c</fullName>
        <label>Showing</label>
        <referenceTo>Showing__c</referenceTo>
        <relationshipLabel>Trailers</relationshipLabel>
        <relationshipName>Trailers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Trailer</label>
    <nameField>
        <label>Trailer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestShowingTrigger.cls
@isTest public class TestShowingTrigger { 
	static testmethod void TestShowingName(){
		Feature__c f = TestDataGenerator.CreateFeaturs(1)[0];
		insert f;
		List<Showing__c> showings = TestDataGenerator.CreateShowings(f.Id, 400);
		insert showings;
		Showing__c showing = [select name, date__c, Start_Time__c from Showing__c where id =: showings[0].Id][0];
		System.assertEquals(String.valueOf(showing.Date__c) + ' ' + showing.Start_Time__c + ' ' + f.Name, showing.Name);
	}

	static testmethod void TestTreilerImpressions(){
		List<Feature__c> features = TestDataGenerator.CreateFeaturs(2);
		insert features;
		List<Showing__c> showings = TestDataGenerator.CreateShowings(features[1].Id, 2);
		insert showings;

		List<Trailer__c> trailers = new List<Trailer__c>();
		trailers.add(TestDataGenerator.CreateTrailer(features[0].Id, showings[0].Id));
		trailers.add(TestDataGenerator.CreateTrailer(features[0].Id, showings[1].Id));
		insert trailers;

		showings[0].tickets_sold__c = 100;
		showings[0].start_time__c = '7:00 PM';
		update showings[0];
		showings[1].tickets_sold__c = 500;
		showings[1].start_time__c = '9:30 PM';
		update showings[1];
		Feature__c savedFeature = [select Trailer_Impressions__c from Feature__c where id =: features[0].id];
		System.assertEquals(600, savedFeature.Trailer_Impressions__c);

		delete showings;
		savedFeature = [select Trailer_Impressions__c from Feature__c where id =: features[0].id];
		System.assertEquals(0, savedFeature.Trailer_Impressions__c);

		undelete showings;
		savedFeature = [select Trailer_Impressions__c from Feature__c where id =: features[0].id];
		System.assertEquals(600, savedFeature.Trailer_Impressions__c);
	}
}