objects/Feature__c.object
<CustomObject>
    <description>A movie being shown</description>
    <fields>
        <fullName>Genre__c</fullName>
        <label>Genre</label>
        <picklist>
            <picklistValues>
                <fullName>Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adventure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comedy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Horror</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Musical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science Fiction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>War</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Release_Date__c</fullName>
        <label>Release Date</label>
        <type>Date</type>
    </fields>
    <label>Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Showing__c.object
<CustomObject>
    <description>The playing of a Feature in a Theatre</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Feature__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feature</label>
        <referenceTo>Feature__c</referenceTo>
        <relationshipLabel>Showings</relationshipLabel>
        <relationshipName>Showings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <picklist>
            <picklistValues>
                <fullName>4:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30 PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Showing</label>
    <nameField>
        <label>Showing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Trailer__c.object
<CustomObject>
    <description>A one-minute preview of a to-be-released Feature that is shown prior to the primary Feature of a Showing.</description>
    <fields>
        <fullName>Feature__c</fullName>
        <label>Feature</label>
        <referenceTo>Feature__c</referenceTo>
        <relationshipLabel>Trailers</relationshipLabel>
        <relationshipName>Trailers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Showing__c</fullName>
        <label>Showing</label>
        <referenceTo>Showing__c</referenceTo>
        <relationshipLabel>Trailers</relationshipLabel>
        <relationshipName>Trailers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Trailer</label>
    <nameField>
        <label>Trailer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestDataGenerator.cls
public class TestDataGenerator { 
	public static List<Feature__c> CreateFeaturs(integer numOfFeatures){
		List<Feature__c> features = new List<Feature__c>();
		for(integer i = 1; i <= numOfFeatures; i++){
			features.add(CreateFeature('Test Feature Name ' + i, null, null));
		}
		return features;
	}

	public static Feature__c CreateFeature(String fName, String genre, Date releaseDate){
		return new Feature__c(name = fName, genre__c = genre, release_date__c = releaseDate);
	}

	public static List<Showing__c> CreateShowings(ID featureId, integer numOfShowings){
		List<Showing__c> showings = new List<Showing__c>();
		for(integer i = 1; i <= numOfShowings; i++){
			showings.add(new Showing__c(Feature__c = featureId, Date__c = Date.today(), Start_Time__c = '9:30'));
		}
		return showings;
	}

	public static Trailer__c CreateTrailer(ID featureId, ID showingID){
		return new Trailer__c(Feature__c = featureId, Showing__c = showingId);
	}
}